// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/auth/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/auth/service.go -destination=internal/app/auth/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"pvz_service/internal/app/auth"
	jwt "pvz_service/pkg/jwt"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ServiceCreateUser mocks base method.
func (m *MockServiceInterface) ServiceCreateUser(ctx context.Context, registerRequest *auth.RegisterRequest) (*auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceCreateUser", ctx, registerRequest)
	ret0, _ := ret[0].(*auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceCreateUser indicates an expected call of ServiceCreateUser.
func (mr *MockServiceInterfaceMockRecorder) ServiceCreateUser(ctx, registerRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceCreateUser", reflect.TypeOf((*MockServiceInterface)(nil).ServiceCreateUser), ctx, registerRequest)
}

// ServiceDummyLogin mocks base method.
func (m *MockServiceInterface) ServiceDummyLogin(ctx context.Context, dummyRequest *auth.DummyLoginRequest) (*jwt.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceDummyLogin", ctx, dummyRequest)
	ret0, _ := ret[0].(*jwt.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceDummyLogin indicates an expected call of ServiceDummyLogin.
func (mr *MockServiceInterfaceMockRecorder) ServiceDummyLogin(ctx, dummyRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceDummyLogin", reflect.TypeOf((*MockServiceInterface)(nil).ServiceDummyLogin), ctx, dummyRequest)
}

// ServiceLoginUser mocks base method.
func (m *MockServiceInterface) ServiceLoginUser(ctx context.Context, loginRequest *auth.LoginRequest) (*jwt.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceLoginUser", ctx, loginRequest)
	ret0, _ := ret[0].(*jwt.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceLoginUser indicates an expected call of ServiceLoginUser.
func (mr *MockServiceInterfaceMockRecorder) ServiceLoginUser(ctx, loginRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceLoginUser", reflect.TypeOf((*MockServiceInterface)(nil).ServiceLoginUser), ctx, loginRequest)
}
