// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/product/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/product/service.go -destination=internal/app/product/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	product "pvz_service/internal/app/product"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ServiceAddProduct mocks base method.
func (m *MockServiceInterface) ServiceAddProduct(ctx context.Context, productRequest *product.CreateProductRequest) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAddProduct", ctx, productRequest)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceAddProduct indicates an expected call of ServiceAddProduct.
func (mr *MockServiceInterfaceMockRecorder) ServiceAddProduct(ctx, productRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAddProduct", reflect.TypeOf((*MockServiceInterface)(nil).ServiceAddProduct), ctx, productRequest)
}

// ServiceDeleteProduct mocks base method.
func (m *MockServiceInterface) ServiceDeleteProduct(ctx context.Context, pvzID uuid.UUID) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceDeleteProduct", ctx, pvzID)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceDeleteProduct indicates an expected call of ServiceDeleteProduct.
func (mr *MockServiceInterfaceMockRecorder) ServiceDeleteProduct(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceDeleteProduct", reflect.TypeOf((*MockServiceInterface)(nil).ServiceDeleteProduct), ctx, pvzID)
}
