// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/reception/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/reception/repository.go -destination=internal/app/reception/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reception "pvz_service/internal/app/reception"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepoInterface is a mock of RepoInterface interface.
type MockRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepoInterfaceMockRecorder
	isgomock struct{}
}

// MockRepoInterfaceMockRecorder is the mock recorder for MockRepoInterface.
type MockRepoInterfaceMockRecorder struct {
	mock *MockRepoInterface
}

// NewMockRepoInterface creates a new mock instance.
func NewMockRepoInterface(ctrl *gomock.Controller) *MockRepoInterface {
	mock := &MockRepoInterface{ctrl: ctrl}
	mock.recorder = &MockRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoInterface) EXPECT() *MockRepoInterfaceMockRecorder {
	return m.recorder
}

// CheckOpenReception mocks base method.
func (m *MockRepoInterface) CheckOpenReception(ctx context.Context, pvzID uuid.UUID) (bool, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOpenReception", ctx, pvzID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckOpenReception indicates an expected call of CheckOpenReception.
func (mr *MockRepoInterfaceMockRecorder) CheckOpenReception(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOpenReception", reflect.TypeOf((*MockRepoInterface)(nil).CheckOpenReception), ctx, pvzID)
}

// CheckValidPVZID mocks base method.
func (m *MockRepoInterface) CheckValidPVZID(ctx context.Context, pvzID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckValidPVZID", ctx, pvzID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckValidPVZID indicates an expected call of CheckValidPVZID.
func (mr *MockRepoInterfaceMockRecorder) CheckValidPVZID(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckValidPVZID", reflect.TypeOf((*MockRepoInterface)(nil).CheckValidPVZID), ctx, pvzID)
}

// CloseReception mocks base method.
func (m *MockRepoInterface) CloseReception(ctx context.Context, receptionID uuid.UUID) (*reception.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseReception", ctx, receptionID)
	ret0, _ := ret[0].(*reception.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseReception indicates an expected call of CloseReception.
func (mr *MockRepoInterfaceMockRecorder) CloseReception(ctx, receptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseReception", reflect.TypeOf((*MockRepoInterface)(nil).CloseReception), ctx, receptionID)
}

// CreateReception mocks base method.
func (m *MockRepoInterface) CreateReception(ctx context.Context, arg1 *reception.Reception) (*reception.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReception", ctx, arg1)
	ret0, _ := ret[0].(*reception.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockRepoInterfaceMockRecorder) CreateReception(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockRepoInterface)(nil).CreateReception), ctx, arg1)
}
