// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/reception/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/reception/service.go -destination=internal/app/reception/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reception "pvz_service/internal/app/reception"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ServiceCloseReception mocks base method.
func (m *MockServiceInterface) ServiceCloseReception(ctx context.Context, receptionRequest *reception.CloseReceptionRequest) (*reception.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceCloseReception", ctx, receptionRequest)
	ret0, _ := ret[0].(*reception.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceCloseReception indicates an expected call of ServiceCloseReception.
func (mr *MockServiceInterfaceMockRecorder) ServiceCloseReception(ctx, receptionRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceCloseReception", reflect.TypeOf((*MockServiceInterface)(nil).ServiceCloseReception), ctx, receptionRequest)
}

// ServiceOpenReception mocks base method.
func (m *MockServiceInterface) ServiceOpenReception(ctx context.Context, receptionRequest *reception.OpenReceptionRequest) (*reception.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceOpenReception", ctx, receptionRequest)
	ret0, _ := ret[0].(*reception.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceOpenReception indicates an expected call of ServiceOpenReception.
func (mr *MockServiceInterfaceMockRecorder) ServiceOpenReception(ctx, receptionRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceOpenReception", reflect.TypeOf((*MockServiceInterface)(nil).ServiceOpenReception), ctx, receptionRequest)
}
