// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/pvz/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/pvz/repository.go -destination=internal/app/pvz/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pvz "pvz_service/internal/app/pvz"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreatePVZ mocks base method.
func (m *MockRepository) CreatePVZ(ctx context.Context, arg1 *pvz.PVZ) (*pvz.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePVZ", ctx, arg1)
	ret0, _ := ret[0].(*pvz.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePVZ indicates an expected call of CreatePVZ.
func (mr *MockRepositoryMockRecorder) CreatePVZ(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePVZ", reflect.TypeOf((*MockRepository)(nil).CreatePVZ), ctx, arg1)
}

// GetPVZWithReceptions mocks base method.
func (m *MockRepository) GetPVZWithReceptions(ctx context.Context, startDate, endDate *time.Time, page, limit int) ([]*pvz.PVZWithReceptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZWithReceptions", ctx, startDate, endDate, page, limit)
	ret0, _ := ret[0].([]*pvz.PVZWithReceptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZWithReceptions indicates an expected call of GetPVZWithReceptions.
func (mr *MockRepositoryMockRecorder) GetPVZWithReceptions(ctx, startDate, endDate, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZWithReceptions", reflect.TypeOf((*MockRepository)(nil).GetPVZWithReceptions), ctx, startDate, endDate, page, limit)
}
