// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/pvz/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/pvz/service.go -destination=internal/app/pvz/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pvz "pvz_service/internal/app/pvz"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// ServiceAddPVZ mocks base method.
func (m *MockServiceInterface) ServiceAddPVZ(ctx context.Context, pvzRequest *pvz.CreatePVZRequest) (*pvz.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAddPVZ", ctx, pvzRequest)
	ret0, _ := ret[0].(*pvz.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceAddPVZ indicates an expected call of ServiceAddPVZ.
func (mr *MockServiceInterfaceMockRecorder) ServiceAddPVZ(ctx, pvzRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAddPVZ", reflect.TypeOf((*MockServiceInterface)(nil).ServiceAddPVZ), ctx, pvzRequest)
}

// ServiceGetPVZs mocks base method.
func (m *MockServiceInterface) ServiceGetPVZs(ctx context.Context, startDateStr, endDateStr, page, limit string) ([]*pvz.PVZWithReceptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceGetPVZs", ctx, startDateStr, endDateStr, page, limit)
	ret0, _ := ret[0].([]*pvz.PVZWithReceptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceGetPVZs indicates an expected call of ServiceGetPVZs.
func (mr *MockServiceInterfaceMockRecorder) ServiceGetPVZs(ctx, startDateStr, endDateStr, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceGetPVZs", reflect.TypeOf((*MockServiceInterface)(nil).ServiceGetPVZs), ctx, startDateStr, endDateStr, page, limit)
}
